### PR TITLE
Prevent NoSuchMethodError

### LINKED ISSUE #26: NoSuchMethodError when calling getObjects() on zero results.
Flutter version: 1.16.3

**Describe the bug**
When calling `getObjects` on `AlgoliaQuerySnapshot` will throw `NoSuchMethod error` if the query is empty.

```
E/flutter (32206): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The method 'map' was called on null.
E/flutter (32206): Receiver: null
E/flutter (32206): Tried calling: map<AlgoliaObjectSnapshot>(Closure: (dynamic) => AlgoliaObjectSnapshot)
E/flutter (32206): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
E/flutter (32206): #1      new AlgoliaQuerySnapshot.fromMap (package:algolia/src/query_snapshot.dart:36:10)
E/flutter (32206): #2      AlgoliaQuery.getObjects (package:algolia/src/query.dart:77:33)
```

**Expected behavior**
Null or an empty array should be returned.

### PR DESCRIPTION
**Pull request by kdy1**
Closes #26

### CODE REVIEW

**Comment by shinriyo** [comment]
@knoxpo

**Comment by danielgomezrico** [comment]
@nhathiwala any chance to look at this?

**Comment by danielgomezrico** [comment]
@nhathiwala why was this PR closed and not merged?

**Comment by nhathiwala** [comment]
@danielgomezrico can you compare the latest code, it has overall change in how QuerySnapshot class has new implementation.

**Pull request closed without merging**
