### PR TITLE
Fix knoxpo/dart_algolia#14

### PR DESCRIPTION
**Pull request by kdy1**
The pr removes wrong try-catch block.

### CODE REVIEW

**Comment by kdy1** [comment]
@krhknoxpo Can you merge the pr and publish a new version?

**Comment by SharksT** [comment]
To get working i had to copy your modification and paste it on my local dev and it works. But i really need this to be released in order to install in others pc and such

**Comment by kdy1** [comment]
@SharksT You can my fork like

```yaml

  algolia:
    git: https://github.com/kdy1/dart_algolia.git

```

**Comment by SharksT** [comment]
Oh, thank you!

**Pull request closed without merging**
