### PR TITLE
fix encoding of params of multi query

### LINKED ISSUE #22: Runtime exception when using setHitsPerPage in multi query
Dart version: 2.7.0
Flutter version: v1.12.13+hotfix.6

**Describe the bug**
The following code raises a runtime exception:
```dart
    final queries = App.algolia.multipleQueries;
    queries.addQuery(App.algolia.index('my_index').setHitsPerPage(1));
    queries.getObjects();
```
It looks like the URI constructor when building the request payload needs the values of the query parameters to be `String|Iterable<String>` : https://api.dartlang.org/stable/2.7.0/dart-core/Uri/Uri.html
The value of parameter `hitsPerPage` is an int, so the constructor fails.

### PR DESCRIPTION
**Pull request by tobiwild**
fixes #22

### CODE REVIEW

**Comment by kferstl** [comment]
@nhathiwala @timtraversy would you mind merging this one? :)

**Comment by ashikvashraf** [comment]
Please fix this issue, currently i am running multiple queries in seperate call.

**Comment by timtraversy** [comment]
I'm just a contributor, don't have write access ✍️

**Comment by danielgomezrico** [comment]
@nhathiwala @timtraversy would you mind merging this one? :)

**Comment by chrisparton1991** [comment]
@nhathiwala any reason this was closed instead of merged? Looks like a valid solution to the problem. I tested it locally and it solved my issue.

**Pull request closed without merging**
